#ifndef _STC8A8KXXD4_LQFP64_H
#define _STC8A8KXXD4_LQFP64_H

#define MCU_FAMILY 8
#define MCU_SERIES 'A'
#define MCU_PINS 64
#define STC8A8KxxD4
#define MCU_HAS_ENHANCED_XOSCCR
#define MCU_MAX_FREQ_MHZ 45
#define CHIPID_IN_XDATA
#define MCU_HAS_COMPARATOR
#define COMPARATOR_4P2N
#define MCU_HAS_MDU
#define MCU_HAS_DMA
#define MCU_HAS_LCM
#define NB_UARTS 4
#define PWM_GROUPS 1
#define PWM_CHANNELS 8
#define ADC_CHANNELS 15
#define MCU_HAS_ADCEXCFG
#define SPI_HAS_HIGH_SPEED
#define NB_TIMERS 5

#include <uni-STC/stcmcu.h>

#endif // _STC8A8KXXD4_LQFP64_H
